import './global.css';
import AppLayout from '../components/AppLayout';
import Providers from '../components/Providers';

export const metadata = {
  title: 'UNO',
  description: 'Generated by Baba',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Providers>
          <AppLayout>{children}</AppLayout>
        </Providers>
      </body>
    </html>
  );
}
