import './global.css';

export const metadata = {
  title: 'UNO',
  description: 'Generated by Baba',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
