import './global.css';
import AppLayout from '../components/AppLayout';

export const metadata = {
  title: 'UNO',
  description: 'Generated by Baba',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AppLayout>{children}</AppLayout>
      </body>
    </html>
  );
}
